import type { AdminStrings } from './types';

export const adminStringsES: AdminStrings = {
  dashboard: 'Dashboard',
  personnel: 'Gestión de Personal',
  courses: 'Gestión de Cursos',
  certifications: 'Certificaciones',
  autoAssign: 'Asignación Automática',
  feedback: 'Feedback',
  gamification: 'Gamificación',
  notifications: 'Notificaciones',
  reports: 'Reportes',
  settings: 'Configuración',
  audit: 'Auditoría',
  newCourse: 'Nuevo curso',
  newRole: 'Nuevo cargo',
  newUser: 'Nuevo usuario',
  newDepartment: 'Nuevo departamento',
  newBadge: 'Nueva insignia',
  newNotification: 'Nueva notificación',
  editCourse: 'Editar curso',
  courseEditor: 'Editor de curso',
  save: 'Guardar',
  cancel: 'Cancelar',
  delete: 'Eliminar',
  loading: 'Cargando...',
  search: 'Buscar',
  name: 'Nombre',
  email: 'Correo electrónico',
  description: 'Descripción',
  code: 'Código',
  role: 'Rol',
  employee: 'Empleado',
  admin: 'Administrador',
  active: 'Activo',
  inactive: 'Inactivo',
  totalUsers: 'Usuarios totales',
  totalRoles: 'Cargos totales',
  totalDepartments: 'Departamentos totales',
  totalCourses: 'Cursos totales',
  totalAssignments: 'Asignaciones totales',
  totalCertificates: 'Certificados totales',
  totalBadges: 'Insignias totales',
  totalFeedback: 'Feedbacks totales',
  totalNotifications: 'Notificaciones totales',
  completion: 'Completación promedio',
  noData: 'Sin datos disponibles',
  noTeam: 'No hay miembros registrados',
  noRoles: 'No hay cargos creados',
  noCourses: 'No hay cursos creados',
  noCertificates: 'No hay certificados emitidos',
  noFeedback: 'No hay feedback registrado',
  noBadges: 'No hay insignias creadas',
  noNotifications: 'No hay notificaciones enviadas',
  noSettings: 'No hay configuraciones registradas',
  noAudit: 'No hay registros de auditoría',
  jobRole: 'Cargo',
  jobRoleCol: 'Cargo',
  department: 'Departamento',
  departmentCol: 'Departamento',
  assignedCourses: 'Cursos asignados',
  assignCourse: 'Asignar curso',
  addCourse: 'Agregar curso',
  selectCourse: 'Selecciona un curso',
  selectRole: 'Selecciona un cargo',
  selectDepartment: 'Selecciona un departamento',
  priority: 'Prioridad',
  mandatory: 'Obligatorio',
  optional: 'Opcional',
  deadline: 'Fecha límite',
  deadlineDays: 'Días límite',
  order: 'Orden',
  progress: 'Progreso',
  status: 'Estado',
  rating: 'Calificación',
  difficulty: 'Dificultad',
  recommend: 'Recomendaría',
  points: 'Puntos',
  category: 'Categoría',
  criteria: 'Criterios',
  iconUrl: 'URL del ícono',
  badgeName: 'Nombre de la insignia',
  badgeDesc: 'Descripción de la insignia',
  title: 'Título',
  message: 'Mensaje',
  type: 'Tipo',
  action: 'Acción',
  entityType: 'Tipo de entidad',
  user: 'Usuario',
  date: 'Fecha',
  oldValue: 'Valor anterior',
  newValue: 'Valor nuevo',
  key: 'Clave',
  value: 'Valor',
  isPublic: 'Público',
  general: 'General',
  branding: 'Branding',
  email2: 'Correo',
  security: 'Seguridad',
  modules: 'Módulos',
  resources: 'Recursos',
  exams: 'Exámenes',
  moduleTitle: 'Título del módulo',
  moduleType: 'Tipo de módulo',
  moduleDuration: 'Duración del módulo',
  moduleBody: 'Contenido del módulo',
  addModule: 'Agregar módulo',
  addQuestion: 'Agregar pregunta',
  addResource: 'Agregar recurso',
  questionText: 'Pregunta',
  options: 'Opciones (una por línea)',
  correctOption: 'Índice de respuesta correcta (0-based)',
  resourceTitle: 'Título del recurso',
  resourceUrl: 'URL del archivo',
  resourceType: 'Tipo de archivo',
  courseTitle: 'Título del curso',
  courseDescription: 'Descripción',
  courseCategory: 'Categoría',
  courseDuration: 'Duración',
  courseImage: 'URL de imagen',
  courseIcon: 'Ícono',
  courseAccent: 'Color de acento',
  saveCourse: 'Guardar curso',
  saveUser: 'Guardar usuario',
  saveRole: 'Guardar cargo',
  saveDepartment: 'Guardar departamento',
  saveBadge: 'Guardar insignia',
  saveNotification: 'Guardar notificación',
  saveSetting: 'Guardar configuración',
  editUser: 'Editar usuario',
  editRole: 'Editar cargo',
  editDepartment: 'Editar departamento',
  personName: 'Nombre',
  personEmail: 'Correo electrónico',
  personPassword: 'Contraseña',
  personRole: 'Rol del usuario',
  roleName: 'Nombre del cargo',
  roleDescription: 'Descripción',
  deptName: 'Nombre del departamento',
  deptCode: 'Código del departamento',
  deptDescription: 'Descripción',
  history: 'Historial de cargos',
  changeRole: 'Cambiar cargo',
  changeRoleReason: 'Razón del cambio',
  noHistory: 'No hay historial de cargos',
  startDate: 'Fecha de inicio',
  endDate: 'Fecha de fin',
  reason: 'Razón',
  currentRole: 'Cargo actual',
  prerequisites: 'Prerrequisitos',
  addPrerequisite: 'Agregar prerrequisito',
  selectPrerequisite: 'Selecciona un curso prerrequisito',
  noPrerequisites: 'No hay prerrequisitos definidos',
  mandatory2: 'Obligatorio',
  autoAssignDesc: 'Asigna cursos automáticamente a empleados según su cargo',
  assignNow: 'Asignar ahora',
  assignedUsers: 'Usuarios asignados',
  courseCol: 'Curso',
  userCol: 'Usuario',
  progressCol: 'Progreso',
  scoreCol: 'Puntaje',
  passed: 'Aprobado',
  failed: 'Reprobado',
  pending: 'Pendiente',
  inProgress: 'En progreso',
  completed: 'Completado',
  overdue: 'Vencido',
  exempted: 'Exento',
  cancelled: 'Cancelado',
  low: 'Baja',
  medium: 'Media',
  high: 'Alta',
  critical: 'Crítica',
  easy: 'Fácil',
  hard: 'Difícil',
  veryEasy: 'Muy fácil',
  veryHard: 'Muy difícil',
  wouldRecommend: 'Lo recomendaría',
  timeAdequate: 'Tiempo adecuado',
  feedbackText: 'Comentario',
  noUserBadges: 'No hay insignias asignadas',
  earnedBy: 'Obtenida por',
  users: 'usuarios',
  badgeCol: 'Insignia',
  sentAt: 'Enviado',
  read: 'Leída',
  unread: 'No leída',
  info: 'Información',
  warning: 'Advertencia',
  success: 'Éxito',
  error: 'Error',
  reminder: 'Recordatorio',
  auditDesc: 'Registro de todas las acciones realizadas en el sistema',
  feedbackDesc: 'Feedback de usuarios sobre los cursos completados',
  gamificationDesc: 'Gestión de insignias y puntos para motivar el aprendizaje',
  notificationsDesc: 'Notificaciones enviadas a los usuarios del sistema',
  reportsDesc: 'Reportes y estadísticas del sistema de aprendizaje',
  settingsDesc: 'Configuración general del sistema',
  certificationsDesc: 'Certificados emitidos y certificaciones de cargo',
  exportExcel: 'Exportar Excel',
  exportPdf: 'Exportar PDF',
  exportCsv: 'Exportar CSV',
  complianceReport: 'Reporte de cumplimiento por cargo',
  progressReport: 'Reporte de progreso individual',
  certReport: 'Reporte de certificaciones',
  feedbackReport: 'Reporte de feedback',
  courseName: 'Nombre del curso',
  userName: 'Nombre del usuario',
  certificateNumber: 'Número de certificado',
  issueDate: 'Fecha de emisión',
  expiryDate: 'Fecha de vencimiento',
  certifiedAt: 'Certificado el',
  isValid: 'Válido',
  expired: 'Expirado',
  valid: 'Válido',
  backToAdmin: 'Volver al panel',
  manageCourses: 'Gestionar cursos',
  manageCourseAction: 'Gestionar curso',
  managePersonnel: 'Gestión de personal',
  manageRoles: 'Gestión de cargos',
  manageAssignments: 'Asignaciones',
  roleManagement: 'Gestión de cargos',
  personnelManagement: 'Gestión de personal',
  deleteConfirm: '¿Seguro que deseas eliminar este elemento?',
  deleteUserConfirm: '¿Seguro que deseas eliminar este usuario?',
  deleteRoleConfirm: '¿Seguro que deseas eliminar este cargo?',
  deleteDeptConfirm: '¿Seguro que deseas eliminar este departamento?',
  deleteBadgeConfirm: '¿Seguro que deseas eliminar esta insignia?',
  deleteNotificationConfirm: '¿Seguro que deseas eliminar esta notificación?',
  saved: 'Guardado correctamente',
  errorSaving: 'Error al guardar',
  personDept: 'Departamento',
  assignToRole: 'Asignar a cargo',
  assignDeadline: 'Fecha límite (opcional)',
  addAssignment: 'Asignar a otro cargo',
  moduleImage: 'URL de imagen',
  moduleVideo: 'URL de video',
  resourceDesc: 'Descripción del recurso',
  explanation: 'Explicación',
  difficultyLevel: 'Dificultad',
  pointsLabel: 'Puntos',
  isDownloadable: 'Descargable',
  showAll: 'Ver todos',
  filterByRole: 'Filtrar por cargo',
  filterByDept: 'Filtrar por departamento',
  allRoles: 'Todos los cargos',
  allDepts: 'Todos los departamentos',
  allStatuses: 'Todos los estados',
  statsOverview: 'Resumen general',
  recentActivity: 'Actividad reciente',
  viewAll: 'Ver todos',
  courseProgress: 'Progreso del curso',
  examResults: 'Resultados de exámenes',
  totalExams: 'Exámenes totales',
  passRate: 'Tasa de aprobación',
  avgScore: 'Puntaje promedio',
  totalProgress: 'Progreso total',
  activeUsers: 'Usuarios activos',
  inactiveUsers: 'Usuarios inactivos',
  mandatoryCourses: 'Cursos obligatorios',
  optionalCourses: 'Cursos opcionales',
  totalHours: 'Horas totales',
  learningHours: 'Horas de aprendizaje',
  welcome: 'Buenos días',
  adminIntro: 'Gestiona el aprendizaje de tu organización',
  signOut: 'Cerrar sesión',
  adminPanel: 'Administración',
  modulesLabel: 'módulos',
  assignedRole: 'Cargo asignado',
  deadlineCol: 'Fecha límite',
  teamMembers: 'Miembros del equipo',
  totalRolesLower: 'cargos totales',
  courseEditorLabel: 'Editor de curso',
  selectCourseToEdit: 'Selecciona un curso para editar',
  tabs: {
    info: 'Información',
    modules: 'Módulos',
    resources: 'Recursos',
    exams: 'Exámenes',
    assignments: 'Asignaciones',
    prerequisites: 'Prerrequisitos',
  },
  personnelTabs: {
    employees: 'Empleados',
    departments: 'Departamentos',
    roles: 'Cargos',
    history: 'Historial',
    requirements: 'Requisitos por cargo',
  },
};
